### Obtener todos los usuarios
GET http://localhost:1234/users

### Obtener un usuario por id
GET http://localhost:1234/users/2

### Crear un usuario
POST http://localhost:1234/users
Content-Type: application/json

{
  "user_name": "Joshua",
  "user_last_name": "Zamora",
  "user_email": "slayther.zr@gmail.com",
  "user_nickname": "joshua",
  "password": "130203",
  "user_type": 0
}

### Actualizar un usuario
PATCH http://localhost:1234/users/10
Content-Type: application/json

{
  "user_name": "Slayther",
  "user_last_name": "Zamora",
  "user_email": "test@test.com"
}

### Eliminar un usuario
DELETE http://localhost:1234/users/10